// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mkDotPlotMatrix
NumericMatrix mkDotPlotMatrix(std::string seq1, std::string seq2, int wsize, int wstep, int nmatch);
RcppExport SEXP dotplot_mkDotPlotMatrix(SEXP seq1SEXP, SEXP seq2SEXP, SEXP wsizeSEXP, SEXP wstepSEXP, SEXP nmatchSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type seq1(seq1SEXP);
    Rcpp::traits::input_parameter< std::string >::type seq2(seq2SEXP);
    Rcpp::traits::input_parameter< int >::type wsize(wsizeSEXP);
    Rcpp::traits::input_parameter< int >::type wstep(wstepSEXP);
    Rcpp::traits::input_parameter< int >::type nmatch(nmatchSEXP);
    __result = Rcpp::wrap(mkDotPlotMatrix(seq1, seq2, wsize, wstep, nmatch));
    return __result;
END_RCPP
}
// mkDotPlotDataFrame
DataFrame mkDotPlotDataFrame(std::string seq1, std::string seq2, int wsize, int wstep, int nmatch);
RcppExport SEXP dotplot_mkDotPlotDataFrame(SEXP seq1SEXP, SEXP seq2SEXP, SEXP wsizeSEXP, SEXP wstepSEXP, SEXP nmatchSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type seq1(seq1SEXP);
    Rcpp::traits::input_parameter< std::string >::type seq2(seq2SEXP);
    Rcpp::traits::input_parameter< int >::type wsize(wsizeSEXP);
    Rcpp::traits::input_parameter< int >::type wstep(wstepSEXP);
    Rcpp::traits::input_parameter< int >::type nmatch(nmatchSEXP);
    __result = Rcpp::wrap(mkDotPlotDataFrame(seq1, seq2, wsize, wstep, nmatch));
    return __result;
END_RCPP
}
