# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate a dotplot matrix by comparing sequence 1 and sequence 2 using the
#' given window size and percent match
#'
#' @param seq1 The first sequence
#' @param seq2 The second sequence
#' @param wsize The window of the size to use
#' @param wstep the size in chars for the steps of the moving window. Use wstep == wsize for non-overlapping windows.
#' @param nmatch if the number of match per window is greater than or equal to nmatch then a dot is produced.
#' @return Returns a matrix
#' @export
mkDotPlotMatrix <- function(seq1, seq2, wsize, wstep, nmatch) {
    .Call('dotplot_mkDotPlotMatrix', PACKAGE = 'dotplot', seq1, seq2, wsize, wstep, nmatch)
}

#' Generate a dotplot matrix by comparing sequence 1 and sequence 2 using the
#' given window size and percent match
#'
#' @param seq1 The first sequence
#' @param seq2 The second sequence
#' @param wsize The window of the size to use
#' @param wstep the size in chars for the steps of the moving window. Use wstep == wsize for non-overlapping windows.
#' @param nmatch if the number of match per window is greater than or equal to nmatch then a dot is produced.
#' @return Returns a matrix
#' @export
mkDotPlotDataFrame <- function(seq1, seq2, wsize, wstep, nmatch) {
    .Call('dotplot_mkDotPlotDataFrame', PACKAGE = 'dotplot', seq1, seq2, wsize, wstep, nmatch)
}

